In [11]:
# 1. Write a Python Program to Add Two Matrices?

import numpy as np

A = np.array([[1,2,3],[4,7,3]])
B = np.array([[6,9,1],[12,54,61]])

print(f"Sum of matrix is {A + B} ")
        


Sum of matrix is [[ 7 11  4]
 [16 61 64]] 


In [16]:
# 2. Write a Python Program to Multiply Two Matrices?

# FOr same order matrix

# C = np.array([[23,56],[12,8]])
# D = np.array([[10,21],[1,8]])

# print(C.shape[1])  #it gives m value of shape (or n x m) of the array
# print(D.shape[0])

# if C.shape[1] == D.shape[0]:
#     print("Multiply of Matrics:")
#     print(np.dot(C, D))
    
 
C = np.array([[23,56],[12,8],[2,5]])
D = np.array([[10,21,4],[1,8,6]])


print(C.shape[1])  #it gives m value of shape (or n x m) of the array
print(D.shape[0])  

if C.shape[1] == D.shape[0]:
    print("Multiply of Matrics:")
    print(np.dot(C, D))
    
else:
    print("Matrix dimention is not correct")

2
2
Multiply of Matrics:
[[286 931 428]
 [128 316  96]
 [ 25  82  38]]


In [17]:
# 3. Write a Python Program to Transpose a Matrix?

M = np.array([[25,50],[11,8],[22,5]])

print(np.transpose(M))

[[25 11 22]
 [50  8  5]]


In [2]:
# 4. Write a Python Program to Sort Words in Alphabetic Order?

words = ["my", "name", "is", "sawan","yadav"]

print(f"words before sorting {words}")

# when we write words in conbination of capital and small latters then sorted will check ASCII code of alphabet then sort

print(f"Words after sorting {sorted(words)}")

words before sorting ['my', 'name', 'is', 'sawan', 'yadav']
Words after sorting ['is', 'my', 'name', 'sawan', 'yadav']


In [23]:
# 5. Write a Python Program to Remove Punctuation From a String?

punchu = '''!, @, #, $, %, ^, &, *, (, ), -, _, +, =, {, }, [, ], |, \, :, ;, ',",,,.,/,?'''

string = "Hello!! this is punctuation {string} .!!!"


nonpunchustring = ""

for ch in string:
    if ch not in punchu:
        nonpunchustring += ch
    
print(f"String without punchuation is   {nonpunchustring}")   # this code retuning results without space


# import string

# def remove_punctuation(string):
#   """Removes punctuation from a string.

#   Args:
#     string: A string.

#   Returns:
#     A string with the punctuation removed.
#   """

# punctuation = string.punctuation
# string_without_punctuation = ""
# for character in string:
#     if character not in punctuation:
#         string_without_punctuation += character
# return string_without_punctuation

# # Example usage:

# string = "This is a test string with punctuation!"

# string_without_punctuation = remove_punctuation(string)

# print(string_without_punctuation)

String without punchuation is   Hellothisispunctuationstring
